### ISSUE TITLE
addAnnotation with just one parameter

### ISSUE THREAD

**Issue by viktornordling** [burningwave/core#2]
I want to add an annotation that looks like this:

```
@Path("/")
```

(where `Path` is `javax.ws.rs.Path`)

But no matter how I try, the best I can get is:

```
@Path( { "/" } )
```

This doesn't work because the `value` in the `Path` annotation is not an array (unlike most other annotations).

Is this a bug?

**Comment by burningwave** [comment]
Ok, soon I will add this feature, for the moment you can use the method `.addOuterCodeLine` e.g.: `.addOuterCodeLine("@Path(\"/\")")`

**Comment by burningwave** [comment]
Solved with version 8.0.0
