### ISSUE TITLE
Spurious build?

### ISSUE THREAD

**Issue by apeteri** [burningwave/core#32]
Hi @Roberto-Gentili,

I'm not sure what exactly happened here: https://github.com/burningwave/core/actions/runs/7002928261

I starred the repository but as a visitor I don't have any actions visible on the UI to kick off a build. Yet I got a notification of the action failing a few minutes later.

Regards,
András

**Comment by apeteri** [comment]
Ah, it seems this workflow is triggered on the "star repository" event: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#watch

> Runs your workflow when the workflow's repository is starred.

https://github.com/burningwave/core/blob/c04dd869e41a2ddc518ae6481618f1e9ae87ef8b/.github/workflows/%5BM%5D%20build%20and%20test%2C%20compute%20coverage%2C%20release.yml#L3-L5

**Comment by Roberto-Gentili** [comment]
The aforementioned workflow is performed with each star received: in reality it must only be activated by the project administrators and is used to allow manual release.
Thanks for the heads up!
