### ISSUE TITLE
Infinite recursion possible when compile fails and will not succeed

### ISSUE THREAD

**Issue by gregorydgraham** [burningwave/core#5]
Compiling multiple classes where a new class references another new class will fail with a class not found error and never succeed.

This causes BurningWave to infinitely recurse at JavaMemoryCompilerImpl.java:231 and chew up CPU.

Adding a maximum number of attempts check avoids the infinite recursion and passes all the tests

**Comment by burningwave** [comment]
Hello, Thanks for reporting, could you give me the code to reproduce this issue?

**Comment by burningwave** [comment]
> Compiling multiple classes where a new class references another new class will fail with a class not found error and never succeed.
> 
> This causes BurningWave to infinitely recurse at JavaMemoryCompilerImpl.java:231 and chew up CPU.
> 
> Adding a maximum number of attempts check avoids the infinite recursion and passes all the tests

Hello, thanks for reporting, could you you give me  the code to reproduce this issue?

**Comment by burningwave** [comment]
> Compiling multiple classes where a new class references another new class will fail with a class not found error and never succeed.
> 
> This causes BurningWave to infinitely recurse at JavaMemoryCompilerImpl.java:231 and chew up CPU.
> 
> Adding a maximum number of attempts check avoids the infinite recursion and passes all the tests

Solved with [this commit](https://github.com/burningwave/core/commit/94fd342cf7ebd28a18709217b275754269f3a9be): wait for [for the release of version 8.15.1](https://github.com/burningwave/core/actions/runs/493778882), download it and try again

**Comment by burningwave** [comment]
> Compiling multiple classes where a new class references another new class will fail with a class not found error and never succeed.
> 
> This causes BurningWave to infinitely recurse at JavaMemoryCompilerImpl.java:231 and chew up CPU.
> 
> Adding a maximum number of attempts check avoids the infinite recursion and passes all the tests

Hello, thanks for reporting, solved with [commit e37947501fa7d5154f4abf5a203c6dd6e3e9f429](https://github.com/burningwave/core/commit/e37947501fa7d5154f4abf5a203c6dd6e3e9f429): **wait for [the release of version 8.15.1](https://github.com/burningwave/core/actions/runs/493797695)**, download it and try again

**Comment by burningwave** [comment]
> Compiling multiple classes where a new class references another new class will fail with a class not found error and never succeed.
> 
> This causes BurningWave to infinitely recurse at JavaMemoryCompilerImpl.java:231 and chew up CPU.
> 
> Adding a maximum number of attempts check avoids the infinite recursion and passes all the tests

Hello, thanks for reporting, solved with [commit e37947501fa7d5154f4abf5a203c6dd6e3e9f429](https://github.com/burningwave/core/commit/e37947501fa7d5154f4abf5a203c6dd6e3e9f429): **wait for [the release of version 8.15.1](https://github.com/burningwave/core/actions/runs/493797695)**, download it and try again
